# Generated by Django 3.2.7 on 2022-06-14 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('pid', models.IntegerField(blank=True, verbose_name='Parent ID')),
                ('partner', models.CharField(blank=True, max_length=20, verbose_name='Partner ID')),
                ('img', models.IntegerField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_tree.family')),
                ('parent', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='family_tree.person')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='Name')),
                ('img', models.IntegerField(blank=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_tree.family')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='family_tree.person')),
            ],
            options={
                'ordering': ['parent'],
            },
        ),
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='family_tree.person')),
            ],
        ),
    ]
