# Generated by Django 4.1.3 on 2022-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
