# Generated by Django 4.1.3 on 2022-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parent',
        ),
        migrations.AddField(
            model_name='person',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='children', to='family_tree.person'),
        ),
    ]
