# Generated by Django 4.1.3 on 2022-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0002_remove_person_parent_person_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='children', to='family_tree.person'),
        ),
    ]
