# Generated by Django 4.1.3 on 2022-12-21 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0003_alter_person_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='parent',
        ),
        migrations.AddField(
            model_name='person',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='family_tree.person'),
        ),
    ]
