# Generated by Django 3.2.16 on 2023-01-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0004_remove_person_parent_person_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-children']},
        ),
    ]
