# Generated by Django 3.2.16 on 2023-01-06 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_tree', '0005_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['id']},
        ),
    ]
