name: Deployment Workflow

on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.KEY_ACTIONS  }}
          HOSTNAME : ${{ secrets.HOST_DNS  }}
          USER_NAME : ${{ secrets.USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -T -i private_key ${USER_NAME}@${HOSTNAME}

          sudo docker rm -f $(sudo docker ps -a -q)
          sudo docker rmi -f $(sudo docker images -aq)
          sudo docker pull momen3/momenrepo