name: Deployment Workflow

on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN  }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: family_tree_project/Dockerfile
          tags: ${{ secrets.DOCKERHUB_REPO }}:latest


  job_two:
    name: Deploy
    needs: job_one
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host : ${{ secrets.HOST_DNS  }}
          username : ${{ secrets.USER_NAME  }}
          key: ${{ secrets.KEY_ACTIONS  }}
          script: |
            touch /home/ec2-user/test
            docker rm -f $(sudo docker ps -a -q) || (echo "Container didn't exist so not removed."; exit 0)
            docker rmi -f $(sudo docker images -aq) || (echo "Image didn't exist so not removed."; exit 0)
            docker pull ${{ secrets.DOCKERHUB_REPO }}
            docker build . -t ${{ secrets.DOCKERHUB_REPO }}
            docker run -dp 8000:8000 ${{ secrets.DOCKERHUB_REPO }}