name: Deployment Workflow

on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host : ${{ secrets.HOST_DNS  }}
          username : ${{ secrets.USER_NAME  }}
          key: ${{ secrets.KEY_ACTIONS  }}
          script: |
            sudo docker rm -f $(sudo docker ps -a -q) || True
            sudo docker rmi -f $(sudo docker images -aq) || True
            sudo docker pull momen3/momenrepo
